insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Burpies', 'Cardio');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Jumping Jacks', 'Cardio');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Bear crawls', 'Cardio');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Row', 'Cardio');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Mountain Climbers', 'Cardio');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Squat Jumps', 'Cardio');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Assault Bike', 'Cardio');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Box Jumps', 'Cardio');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Jump Rope', 'Cardio');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Kettlebell Swings', 'Cardio');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Hammer Curls', 'Weights');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Bench Press', 'Weights');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Barbell Deadlift', 'Weights');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Romanian Deadlift', 'Weights');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Lunges', 'Weights');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Overhead Shoulder Press', 'Weights');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Barbell Back Squat', 'Weights');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Bent-over Row', 'Weights');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Bulgarian Squat', 'Weights');
insert into exercise(id, name, type) values (nextval('hibernate_sequence'), 'Dumbbell Front Squat', 'Weights');
